# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: cpr_adressematch 0.2.1 ruby lib

Gem::Specification.new do |s|
  s.name = "cpr_adressematch"
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Anders Johannsen"]
  s.date = "2014-11-20"
  s.description = "Interface for generating and parsing the Danish CPR Registry data files.\n    Support the 'adressematch' protocol, which can be used to query by name and adress as well as\n    by the personal identifical number (CPR)\n    "
  s.email = "anders@johannsen.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/cpr/adressematch/Req1100.rb",
    "lib/cpr/adressematch/Req1200.rb",
    "lib/cpr/adressematch/Req1300.rb",
    "lib/cpr/adressematch/Req1400.rb",
    "lib/cpr/adressematch/Resp000.rb",
    "lib/cpr/adressematch/Resp001.rb",
    "lib/cpr/adressematch/Resp001A.rb",
    "lib/cpr/adressematch/Resp002.rb",
    "lib/cpr/adressematch/Resp003.rb",
    "lib/cpr/adressematch/Resp004.rb",
    "lib/cpr/adressematch/Resp005.rb",
    "lib/cpr/adressematch/Resp010.rb",
    "lib/cpr/adressematch/Resp011.rb",
    "lib/cpr/adressematch/Resp012.rb",
    "lib/cpr/adressematch/Resp013.rb",
    "lib/cpr/adressematch/Resp901.rb",
    "lib/cpr/adressematch/Resp902.rb",
    "lib/cpr/adressematch/Resp903.rb",
    "lib/cpr/adressematch/Resp910.rb",
    "lib/cpr/adressematch/Resp998.rb",
    "lib/cpr/adressematch/Resp999.rb",
    "lib/cpr/alphanumeric_field.rb",
    "lib/cpr/class_generator.rb",
    "lib/cpr/field.rb",
    "lib/cpr/kunderefnr.rb",
    "lib/cpr/numeric_field.rb",
    "lib/cpr/req_document.rb",
    "lib/cpr/resp_document.rb",
    "lib/cpr/row.rb",
    "lib/cpr_adressematch.rb",
    "test/helper.rb",
    "test/test_cpr_adressematch.rb",
    "test/test_cpr_adressematch_resp001.rb",
    "test/test_cpr_alphanumeric_field.rb",
    "test/test_cpr_field.rb",
    "test/test_cpr_numeric_field.rb",
    "test/test_cpr_req_document.rb",
    "test/test_cpr_resp_document.rb",
    "test/test_cpr_row.rb"
  ]
  s.homepage = "http://github.com/andersjo/cpr_adressematch"
  s.rubygems_version = "2.2.2"
  s.summary = "Interface for generating and parsing the Danish CPR Registry data files"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

